package edu.cpp.cs356;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

public class AdminPanel extends javax.swing.JFrame {

    private DefaultTreeModel dtm;
    private DefaultMutableTreeNode rootNode;

    private static AdminPanel instance;

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    public static AdminPanel getInstance() {
        if (instance == null) {
            synchronized (AdminPanel.class) {
                if (instance == null) {
                    instance = new AdminPanel();
                }
            }
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        componentTree = new javax.swing.JTree();
        userId = new javax.swing.JTextField();
        groupId = new javax.swing.JTextField();
        user = new javax.swing.JButton();
        group = new javax.swing.JButton();
        userView = new javax.swing.JButton();
        totalMessage = new javax.swing.JButton();
        totalUser = new javax.swing.JButton();
        totalGroup = new javax.swing.JButton();
        percentage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        verify = new javax.swing.JButton();
        find = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("cs356");
        componentTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(componentTree);

        userId.setText("User ID");
        userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdActionPerformed(evt);
            }
        });

        groupId.setText("Group ID");

        user.setText("Add User");

        group.setText("Add Group");
        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });

        userView.setText("Open User View");

        totalMessage.setText("Show Messages Total");
        totalMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMessageActionPerformed(evt);
            }
        });

        totalUser.setText("Show User Total");
        totalUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUserActionPerformed(evt);
            }
        });

        totalGroup.setText("Show Group Total");
        totalGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGroupActionPerformed(evt);
            }
        });

        percentage.setText("Show Positive Percentage");
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });

        message.setColumns(20);
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        verify.setText("ID Verification");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        find.setText("Find the last updated User");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupId)
                            .addComponent(group, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userView, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(find, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(verify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalUser)
                            .addComponent(totalGroup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalMessage)
                            .addComponent(percentage)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed
        String id = userId.getText();
        if (!id.equals("")) {
            dtm = (DefaultTreeModel) componentTree.getModel();
            Component user = new User(id);
            DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(user);
            DefaultMutableTreeNode parentNode = getParentNode();
            dtm.insertNodeInto(childNode, parentNode, parentNode.getChildCount());
            dtm.reload();
        } else {
            message.setText("Please enter a valid name");
        }
    }//GEN-LAST:event_userIdActionPerformed

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        String id = groupId.getText();
        if (!id.equals("")) {
            dtm = (DefaultTreeModel) componentTree.getModel();
            Component group = new Group(id);
            DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(group);
            DefaultMutableTreeNode parentNode = getParentNode();
            dtm.insertNodeInto(childNode, parentNode, parentNode.getChildCount());
            dtm.reload();
        } else {
            message.setText("Please enter a valid name");
        }
    }//GEN-LAST:event_groupActionPerformed

    private void totalUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUserActionPerformed
        ComponentVisitor cv = new ComponentVisitor();
        message.setText("Total User: " + String.valueOf(cv.getTotalUsers()));
    }//GEN-LAST:event_totalUserActionPerformed

    private void totalGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGroupActionPerformed
        ComponentVisitor cv = new ComponentVisitor();
        message.setText("Total Group: " + String.valueOf(cv.getTotalGroups()));
    }//GEN-LAST:event_totalGroupActionPerformed

    private void totalMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMessageActionPerformed
        TweetVisitor tv = new TweetVisitor();
        message.setText("Total Message: " + String.valueOf(tv.getTotalTweets()));
    }//GEN-LAST:event_totalMessageActionPerformed

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
        TweetVisitor tv = new TweetVisitor();
        message.setText("Postive Percentage: " + String.valueOf(tv.calcPercentage()));
    }//GEN-LAST:event_percentageActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        message.setText("All the IDs are valid");
    }//GEN-LAST:event_verifyActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        message.setText("The last updated user is: ");
    }//GEN-LAST:event_findActionPerformed

    private DefaultMutableTreeNode getParentNode() {
        DefaultMutableTreeNode selectedNode = getSelectedNode();
        if (selectedNode != null) {
            if (selectedNode.getAllowsChildren()) {
                return selectedNode;
            }
            return (DefaultMutableTreeNode) selectedNode.getParent();
        }
        return rootNode;
    }

    private DefaultMutableTreeNode getSelectedNode() {
        TreePath selectedPath = componentTree.getSelectionPath();
        if (selectedPath != null) {
            return (DefaultMutableTreeNode) (selectedPath.getLastPathComponent());
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree componentTree;
    private javax.swing.JButton find;
    private javax.swing.JButton group;
    private javax.swing.JTextField groupId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea message;
    private javax.swing.JButton percentage;
    private javax.swing.JButton totalGroup;
    private javax.swing.JButton totalMessage;
    private javax.swing.JButton totalUser;
    private javax.swing.JButton user;
    private javax.swing.JTextField userId;
    private javax.swing.JButton userView;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables

}
